/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.ClienteDAO;
import DAO.ConexaoDAO;
import DAO.ProdutoDAO;
import DAO.VendasDAO;
import DTO.ClienteDTO;
import DTO.ProdutoDTO;
import DTO.RelatorioVendaDTO;
import DTO.VendasClienteDTO;
import DTO.VendasDTO;
import controller.ControllerCliente;
import controller.ControllerProduto;
import controller.ControllerVendasCliente;
import controller.VendasController;
import java.awt.event.ItemEvent;
import java.sql.Connection;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import static java.time.temporal.TemporalQueries.localDate;
import java.util.ArrayList;
import java.util.Date;

import java.util.List;
import java.util.Locale;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

import org.apache.log4j.Logger;
import static org.hibernate.criterion.Order.desc;
import sun.util.logging.PlatformLogger;

/**
 *
 * @author josia
 */
public class TelaRelatorio extends javax.swing.JFrame {

    ControllerCliente controllerCliente = new ControllerCliente();
    ControllerProduto controllerProduto = new ControllerProduto();
    VendasController vendasController = new VendasController();
    ClienteDAO clientedao = new ClienteDAO();
    ProdutoDAO produtodao = new ProdutoDAO();
    ArrayList<ClienteDTO> PesquisarCliente = new ArrayList<>();
    ArrayList<ClienteDTO> PesquisarcampoCliente = new ArrayList<>();
    ArrayList<ProdutoDTO> PesquisarProduto = new ArrayList<>();
    ArrayList<VendasClienteDTO> listadtovendascliente = new ArrayList<>();
    ProdutoDTO produtodto = new ProdutoDTO();
    ControllerVendasCliente controllerVendasCliente = new ControllerVendasCliente();
    VendasDAO vendasdao = new VendasDAO();
    PreparedStatement pstm;
    ResultSet rs;
    Connection conn = null;

    /**
     * Creates new form TelaRelatorio
     */
    public TelaRelatorio() {
        initComponents();

        conn = new ConexaoDAO().conectaBD();
        // pesquisarVendasDesc(jFormattedDataVenda.getText());
        // pesquisarVendas();

        //carregarVendas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaRelatorio = new javax.swing.JTable();
        btnImprimirVendas = new javax.swing.JButton();
        txtTotalVendaRela = new javax.swing.JTextField();
        btnPesquisarDesc = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtDataVendaInicio = new javax.swing.JFormattedTextField();
        txtDataVendaFim = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(255, 235, 175));

        jPanel3.setBackground(new java.awt.Color(255, 235, 175));
        jPanel3.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("RELATÓRIOS DE VENDAS");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        tabelaRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATA", "NOME PRODUTO", "QUANTIDADE", "FORMA PAGAMENTO", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaRelatorioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaRelatorio);

        btnImprimirVendas.setText("IMPRIMIR VENDAS");
        btnImprimirVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirVendasActionPerformed(evt);
            }
        });

        txtTotalVendaRela.setEditable(false);
        txtTotalVendaRela.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTotalVendaRelaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTotalVendaRelaFocusLost(evt);
            }
        });
        txtTotalVendaRela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalVendaRelaActionPerformed(evt);
            }
        });
        txtTotalVendaRela.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTotalVendaRelaKeyReleased(evt);
            }
        });

        btnPesquisarDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesq cópia.PNG"))); // NOI18N
        btnPesquisarDesc.setText("PESQUISAR");
        btnPesquisarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarDescActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("TOTAL DE VENDAS");

        try {
            txtDataVendaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataVendaInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataVendaInicioActionPerformed(evt);
            }
        });

        try {
            txtDataVendaFim.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("SAIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("DATA INICIO");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("DATA FIM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDataVendaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataVendaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnPesquisarDesc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnImprimirVendas))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalVendaRela, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimirVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPesquisarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataVendaFim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataVendaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txtTotalVendaRela, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(790, 528));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabelaRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaRelatorioMouseClicked
        //    PesquisarVendas();
    }//GEN-LAST:event_tabelaRelatorioMouseClicked

    private void btnImprimirVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirVendasActionPerformed
        // IMPRIMIR RELATÓRIO

        int confirma = JOptionPane.showConfirmDialog(null, "Confirma a impressão deste relatório?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            try {
                JasperPrint print = JasperFillManager.fillReport("C:/reports/vendas.jasper", null, conn);
                JasperViewer.viewReport(print, false);

            } catch (Exception erro) {
                JOptionPane.showMessageDialog(null, erro);
            }
        }

    }//GEN-LAST:event_btnImprimirVendasActionPerformed

    private void btnPesquisarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarDescActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data_inicio = LocalDate.parse(txtDataVendaInicio.getText(), formato);
        LocalDate data_fim = LocalDate.parse(txtDataVendaFim.getText(), formato);
        VendasDAO objvendadao = new VendasDAO();
        List<RelatorioVendaDTO> lista = objvendadao.pesquisarVendasDesc(data_inicio, data_fim);
        DefaultTableModel relatorio = (DefaultTableModel) tabelaRelatorio.getModel();
        relatorio.setNumRows(0);
        for (RelatorioVendaDTO v : lista) {
            relatorio.addRow(new Object[]{
                v.getData(),
                v.getNomeProduto(),
                v.getQuantidade(),
                v.getFormaPagamento(),
                v.getValorTotal()
            });
            SomarValorTotalVendas();
        }

        /*
        try {
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
           String data_inicio = txtDataVendaInicio.getText();
           String data_fim = txtDataVendaFim.getText();
           
         //  LocalDate localDate = LocalDate.parse(date,formato);

            LocalDate localdate = LocalDate.parse(data_inicio, formato);
            LocalDate localdate1 = LocalDate.parse(data_fim, formato);
            VendasDAO objvendadao = new VendasDAO();
            //  List<VendasDTO> lista = objvendadao.pesquisarVendasDesc(data_inicio, data_fim);

            // VendasDAO objvendadao = new VendasDAO();
            //model.setNumRows(1);
            List<VendasDTO> lista = objvendadao.pesquisarVendasDesc(localdate, localdate1);

            DefaultTableModel relatorio = (DefaultTableModel) tabelaRelatorio.getModel();
            //relatorio.setNumRows(1);
            for (int num = 0; num < lista.size(); num++) {
                relatorio.addRow(new Object[]{
                    lista.get(num).getDatavenda(),
                    lista.get(num).getCodigoProduto(),
                    lista.get(num).getQuantidade(),
                    lista.get(num).getFormapagamento(),
                    lista.get(num).getValortotalapagar(),});
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores VIEW: " + erro);

        }
         */
    }//GEN-LAST:event_btnPesquisarDescActionPerformed

    private void txtTotalVendaRelaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalVendaRelaFocusGained
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTotalVendaRelaFocusGained

    private void txtTotalVendaRelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalVendaRelaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalVendaRelaActionPerformed

    private void txtTotalVendaRelaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTotalVendaRelaFocusLost
        // TODO add your handling code here:
        //SomarValorTotalVendas();
    }//GEN-LAST:event_txtTotalVendaRelaFocusLost

    private void txtTotalVendaRelaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTotalVendaRelaKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_txtTotalVendaRelaKeyReleased

    private void txtDataVendaInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataVendaInicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataVendaInicioActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TelaMenu objtelamenu = new TelaMenu();
        objtelamenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimirVendas;
    private javax.swing.JButton btnPesquisarDesc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaRelatorio;
    private javax.swing.JFormattedTextField txtDataVendaFim;
    private javax.swing.JFormattedTextField txtDataVendaInicio;
    private javax.swing.JTextField txtTotalVendaRela;
    // End of variables declaration//GEN-END:variables

//
    /*PESQUISAR (PARA APARECER OS DADOS NA TABELA)
    private void pesquisarVendas() {
        try {
            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate data_inicio = LocalDate.parse(txtDataVendaInicio.getText(), formato);
            LocalDate data_fim = LocalDate.parse(txtDataVendaFim.getText(), formato);
            VendasDAO objvendadao = new VendasDAO();
            //  List<VendasDTO> lista = objvendadao.pesquisarVendasDesc(data_inicio, data_fim);

            // VendasDAO objvendadao = new VendasDAO();
            //model.setNumRows(1);
            List<RelatorioVendaDTO> lista = objvendadao.pesquisarVendasDesc(data_inicio, data_fim);

            DefaultTableModel relatorio = (DefaultTableModel) tabelaRelatorio.getModel();
            relatorio.setNumRows(1);
            for (int num = 0; num < lista.size(); num++) {
                relatorio.addRow(new Object[]{
                    lista.get(num).getDatavenda(),
                    lista.get(num).getCodigoProduto(),
                    lista.get(num).getQuantidade(),
                    lista.get(num).getFormapagamento(),
                    lista.get(num).getValortotalapagar(),});
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores VIEW: " + erro);

        }
        */
        /*
        try {

            VendasDAO objvendasdao = new VendasDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaRelatorio.getModel();
            //model.setNumRows(1);

            List<RelatorioVendaDTO> lista = objvendasdao.pesquisarVendas();
            for (int num = 1; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getData(),
                    lista.get(num).getNomeProduto(),
                    lista.get(num).getQuantidade(),
                    lista.get(num).getFormaPagamento(),
                    lista.get(num).getValorTotal(),});
            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores VIEW: " + erro);
       
        }
         */
   

    /*

    private void carregarVendas(){
    produtodto = controllerProduto.pesquisarPorCodigo(Integer.parseInt(txtCodigoProduto.getText()));
            DefaultTableModel model = (DefaultTableModel) tabelaVendas.getModel();
            int cont = 0;
            int quantidade = 0;
            quantidade = Integer.valueOf(txtQuantidade.getText());
            for (int i = 0; i < cont; i++) {
                model.setNumRows(0);
            }
            model.addRow(new Object[]{
                produtodto.getId(),
                produtodto.getProduto(),
                txtQuantidade.getText(),
                produtodto.getValorvenda(),
}
    }
     */
    //PESQUISAR VENDAS POR DATA DESCRIÇÃO
//    private void pesquisarVendasDesc(String desc) {
//        try {
//            MaskFormatter formatar = new MaskFormatter("##/##/####");
//            jFormattedDataVendaInicio.setFormatterFactory(new DefaultFormatterFactory(formatar));
//
//            VendasDAO objvendasdao = new VendasDAO();
//
//            DefaultTableModel model = (DefaultTableModel) tabelaRelatorio.getModel();
//            model.setNumRows(1);
//
//            List<RelatorioVendaDTO> lista = objvendasdao.pesquisarVendasDesc(desc);
//            for (int num = 1; num < lista.size(); num++) {
//                model.addRow(new Object[]{
//                    lista.get(num).getData(),
//                    lista.get(num).getNomeProduto(),
//                    lista.get(num).getQuantidade(),
//                    lista.get(num).getFormaPagamento(),
//                    lista.get(num).getValorTotal(),
//                });
//            }
//        } catch (ParseException ex) {
//            java.util.logging.Logger.getLogger(TelaRelatorio.class.getName()).log(Level.SEVERE, null, ex);
//        }
//      

    //soma total de vendas
    private void SomarValorTotalVendas() {
        double soma = 0, valor;
        int cont = tabelaRelatorio.getRowCount();
        for (int i = 0; i < cont; i++) {
            valor = (double) tabelaRelatorio.getValueAt(i, 4);
            soma = soma + valor;
        }
        txtTotalVendaRela.setText(String.valueOf(soma));
    }
    //             
/*
    public void pequisarPorDesc() {
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate data_inicio = LocalDate.parse(txtDataVendaInicio.getText(), formato);
        LocalDate data_fim = LocalDate.parse(txtDataVendaFim.getText(), formato);
        VendasDAO objvendadao = new VendasDAO();
        List<VendasDTO> lista = objvendadao.pesquisarVendasDesc(data_inicio, data_fim);
        DefaultTableModel relatorio = (DefaultTableModel) tabelaRelatorio.getModel();
        for (int num = 1; num < lista.size(); num++) {
            relatorio.addRow(new Object[]{
                lista.get(num).getDatavenda(),
                lista.get(num).getCodigoProduto(),
                lista.get(num).getQuantidade(),
                lista.get(num).getFormapagamento(),
                lista.get(num).getValortotalapagar(), // relatorio.setNumRows(0);
            //for(RelatorioVendaDTO v : lista){
            //             relatorio.addRow(new Object[]{
            //                 v.getData(),
            //                 v.getNomeProduto(),
            //                 v.getQuantidade(),
            //                 v.getFormaPagamento(),
            //                 v.getValorTotal()
            });
        }
 }
*/

}

