/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.FornecedorDAO;
import DTO.FornecedorDTO;
import DTO.ProdutoDTO;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author josia
 */
public class TelaCadastroFornecedor extends javax.swing.JFrame {
    
    Connection conn;
    PreparedStatement pstm;
    ResultSet rs;

    /**
     * Creates new form TelaCadastroCliente
     */
    public TelaCadastroFornecedor() {
        initComponents();
        PesquisarFornecedor();
        LimparCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtId_Fornecedor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtNome_Fornecedor = new javax.swing.JTextField();
        txtCpf_Fornecedor = new javax.swing.JTextField();
        txtEndereco_Fornecedor = new javax.swing.JTextField();
        txtProduto_Fornecedor = new javax.swing.JTextField();
        txtEmail_Fornecedor = new javax.swing.JTextField();
        txtContato_Fornecedor1 = new javax.swing.JTextField();
        txtContato_Fornecedor2 = new javax.swing.JTextField();
        txtPesquisarFornecDesc = new javax.swing.JTextField();
        btnBucarFornecDesc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaFornecedor = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(255, 235, 175));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        jLabel1.setText("CADASTRO DE FORNECEDOR");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-menu-de-usuário-masculino-30.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 526, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(410, 410, 410))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 9, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 235, 175));
        jPanel2.setPreferredSize(new java.awt.Dimension(202, 405));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/JV - SISTAMASCADAST.png"))); // NOI18N

        btnCadastrar.setBackground(new java.awt.Color(204, 255, 204));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExcluir.setText("EXCLUIR");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSair.setText("SAIR");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSair, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(btnExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jPanel3.setBackground(new java.awt.Color(255, 235, 175));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel4.setText("CODIGO");

        txtId_Fornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtId_Fornecedor.setEnabled(false);

        jLabel5.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel5.setText("NOME");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel6.setText("CPF/CNPJ");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel7.setText("PRODUTO QUE FORNECE");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel8.setText("E-MAIL");

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel9.setText("ENDEREÇO");

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel10.setText("CONTATO 1");

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel11.setText("CONTATO 2");

        txtNome_Fornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtCpf_Fornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtEndereco_Fornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtProduto_Fornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtProduto_Fornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProduto_FornecedorActionPerformed(evt);
            }
        });

        txtEmail_Fornecedor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtContato_Fornecedor1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtContato_Fornecedor2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        btnBucarFornecDesc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnBucarFornecDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesq cópia.PNG"))); // NOI18N
        btnBucarFornecDesc.setText("BUSCAR");
        btnBucarFornecDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBucarFornecDescActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtPesquisarFornecDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBucarFornecDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNome_Fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtEndereco_Fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtCpf_Fornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(txtId_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(22, 22, 22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEmail_Fornecedor)
                            .addComponent(txtProduto_Fornecedor)
                            .addComponent(txtContato_Fornecedor1)
                            .addComponent(txtContato_Fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(81, 81, 81))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisarFornecDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBucarFornecDesc))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtProduto_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtEmail_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtContato_Fornecedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtContato_Fornecedor2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtId_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtCpf_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEndereco_Fornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tabelaFornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "NOME", "CPF/CNPJ", "ENDEREÇO", "PRODUTO QUE FORNECE", "E-MAIL", "CONTATO 1", "CONTATO 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaFornecedorMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tabelaFornecedorMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaFornecedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
        );

        setBounds(0, 0, 1345, 774);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProduto_FornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProduto_FornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProduto_FornecedorActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        TelaMenu objtelamenu = new TelaMenu();
        objtelamenu.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnSairActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed

        CadastrarFornecedor();
        PesquisarFornecedor();
        LimparCampos();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AlterarProduto();
        LimparCampos();
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void tabelaFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFornecedorMouseClicked

        if (tabelaFornecedor.getSelectedRow() != -1) {

            
            txtId_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 0).toString());
            txtNome_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 1).toString());
            txtCpf_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 2).toString());
            txtEndereco_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 3).toString());
            txtProduto_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(),4).toString());
            txtEmail_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 5).toString());
            txtContato_Fornecedor1.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 6).toString());
            txtContato_Fornecedor2.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 7).toString());

        }
    }//GEN-LAST:event_tabelaFornecedorMouseClicked

    private void tabelaFornecedorMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaFornecedorMouseReleased
        if (tabelaFornecedor.getSelectedRow() != -1) {

            txtId_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 0).toString());
            txtNome_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 1).toString());
            txtCpf_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 2).toString());
            txtEndereco_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(),3).toString());
            txtProduto_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 4).toString());
            txtEmail_Fornecedor.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 5).toString());
            txtContato_Fornecedor1.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(),6).toString());
            txtContato_Fornecedor2.setText(tabelaFornecedor.getValueAt(tabelaFornecedor.getSelectedRow(), 7).toString());

        }
    }//GEN-LAST:event_tabelaFornecedorMouseReleased

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        ExcluirFornecedor();
        PesquisarFornecedor();
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnBucarFornecDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBucarFornecDescActionPerformed
        // TODO add your handling code here:
        PesquisarFornecedorDesc(txtPesquisarFornecDesc.getText());
    }//GEN-LAST:event_btnBucarFornecDescActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBucarFornecDesc;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaFornecedor;
    private javax.swing.JTextField txtContato_Fornecedor1;
    private javax.swing.JTextField txtContato_Fornecedor2;
    private javax.swing.JTextField txtCpf_Fornecedor;
    private javax.swing.JTextField txtEmail_Fornecedor;
    private javax.swing.JTextField txtEndereco_Fornecedor;
    private javax.swing.JTextField txtId_Fornecedor;
    private javax.swing.JTextField txtNome_Fornecedor;
    private javax.swing.JTextField txtPesquisarFornecDesc;
    private javax.swing.JTextField txtProduto_Fornecedor;
    // End of variables declaration//GEN-END:variables

    private void CadastrarFornecedor() {

        String nome_fornecedor, cpf_fornecedor, endereco_fornecedor, produto_fornecedor,
                email_fornecedor,contato_fornecedor1,contato_fornecedor2;
      //  int id_fornecedor;
        
      //  id_fornecedor = Integer.parseInt(txtId_Fornecedor.getText());
//        ProdutoDTO objprodutodto = new ProdutoDTO();
//        ProdutoDTO objproduto = new ProdutoDTO();
//        objprodutodto = (ProdutoDTO)
        nome_fornecedor = txtNome_Fornecedor.getText();
        cpf_fornecedor = txtCpf_Fornecedor.getText();
        endereco_fornecedor = txtEndereco_Fornecedor.getText();
        produto_fornecedor = txtProduto_Fornecedor.getText();
        email_fornecedor = txtEmail_Fornecedor.getText();
        contato_fornecedor1 = txtContato_Fornecedor1.getText();
        contato_fornecedor2 = txtContato_Fornecedor2.getText();

        FornecedorDTO objfornecedordto = new FornecedorDTO();

     //   objfornecedordto.setId_fornecedor(id_fornecedor);
        objfornecedordto.setNome_fornecedor(nome_fornecedor);
        objfornecedordto.setCpf_fornecedor(cpf_fornecedor);
        objfornecedordto.setEndereco_fornecedor(endereco_fornecedor);
        objfornecedordto.setProduto_fornecedor(produto_fornecedor);
        objfornecedordto.setEmail_fornecedor(email_fornecedor);      
        objfornecedordto.setContato_fornecedor1(contato_fornecedor1);
        objfornecedordto.setContato_fornecedor2(contato_fornecedor2);
        

        FornecedorDAO objfornecedordao = new FornecedorDAO();
        objfornecedordao.CadastrarFornecedor(objfornecedordto);

    }

    private void PesquisarFornecedor() {
        try {
            FornecedorDAO objprodutodao = new FornecedorDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFornecedor.getModel();
            model.setNumRows(0);

            ArrayList<FornecedorDTO> lista = objprodutodao.PesquisarFornecedor();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_fornecedor(),
                    lista.get(num).getNome_fornecedor(),
                    lista.get(num).getCpf_fornecedor(),
                    lista.get(num).getEndereco_fornecedor(),
                    lista.get(num).getProduto_fornecedor(),
                    lista.get(num).getEmail_fornecedor(),
                    lista.get(num).getContato_fornecedor1(),
                    lista.get(num).getContato_fornecedor2(),});

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores VIEW: " + erro);
        }
    }

    private void AlterarProduto() {

        String nome_fornecedor, endereco_fornecedor, produto_fornecedor,
                email_fornecedor,
                cpf_fornecedor, contato_fornecedor1,
                contato_fornecedor2;
        int id_fornecedor;

        id_fornecedor = Integer.parseInt(txtId_Fornecedor.getText());
        nome_fornecedor = txtNome_Fornecedor.getText();
        endereco_fornecedor = txtEndereco_Fornecedor.getText();
        produto_fornecedor = txtProduto_Fornecedor.getText();
        email_fornecedor = txtEmail_Fornecedor.getText();
        cpf_fornecedor = txtCpf_Fornecedor.getText();
        contato_fornecedor1 = txtContato_Fornecedor1.getText();
        contato_fornecedor2 = txtContato_Fornecedor2.getText();

        FornecedorDTO objfornecedordto = new FornecedorDTO();
        objfornecedordto.setId_fornecedor(id_fornecedor);
        objfornecedordto.setNome_fornecedor(nome_fornecedor);
        objfornecedordto.setEndereco_fornecedor(endereco_fornecedor);
        objfornecedordto.setProduto_fornecedor(produto_fornecedor);
        objfornecedordto.setEmail_fornecedor(email_fornecedor);
        objfornecedordto.setCpf_fornecedor(cpf_fornecedor);
        objfornecedordto.setContato_fornecedor1(contato_fornecedor1);
        objfornecedordto.setContato_fornecedor2(contato_fornecedor2);

        FornecedorDAO objfornecedordao = new FornecedorDAO();
        objfornecedordao.alterarFornecedor(objfornecedordto);

    }
    
    //EXCLUIR PRODUTO
     private void ExcluirFornecedor() {
        int id;

        id = Integer.parseInt(txtId_Fornecedor.getText());

        FornecedorDTO objfornecedordto = new FornecedorDTO();
        objfornecedordto.setId_fornecedor(id);

        FornecedorDAO objprodutodao = new FornecedorDAO();
        objprodutodao.ExcluirFornecedor(objfornecedordto);

     }
    
    
    private void LimparCampos() {
        txtId_Fornecedor.setText("");
        txtNome_Fornecedor.setText("");
        txtEndereco_Fornecedor.setText("");
        txtProduto_Fornecedor.setText("");
        txtEmail_Fornecedor.setText("");
        txtCpf_Fornecedor.setText("");
        txtContato_Fornecedor1.setText("");
        txtContato_Fornecedor2.setText("");
        txtPesquisarFornecDesc.setText("");
        
        txtNome_Fornecedor.requestFocus();

    }

    //pesquisar fornecedor por descriçao
    private void PesquisarFornecedorDesc(String desc) {
        try {
            FornecedorDAO objprodutodao = new FornecedorDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaFornecedor.getModel();
            model.setNumRows(0);

            ArrayList<FornecedorDTO> lista = objprodutodao.PesquisarFornecedorDesc(desc);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId_fornecedor(),
                    lista.get(num).getNome_fornecedor(),
                    lista.get(num).getCpf_fornecedor(),
                    lista.get(num).getEndereco_fornecedor(),
                    lista.get(num).getProduto_fornecedor(),
                    lista.get(num).getEmail_fornecedor(),
                    lista.get(num).getContato_fornecedor1(),
                    lista.get(num).getContato_fornecedor2(),});

            }

        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores VIEW: " + erro);
        }
    }
}
