/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.FornecedorDAO;
import DAO.ProdutoDAO;
import DTO.FornecedorDTO;
import DTO.ProdutoDTO;
import controller.ControllerProduto;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static org.hibernate.criterion.Order.desc;
import util.Formatador;

/**
 *
 * @author josia
 */
public class TelaCadastroProduto extends javax.swing.JFrame {

    ArrayList<FornecedorDTO> PesquisarFornecedor = new ArrayList<>();
    ArrayList<ProdutoDTO> PesquisarProduto = new ArrayList<>();
    ControllerProduto controllerProduto = new ControllerProduto();
    
    PreparedStatement pstm;
    ResultSet rs;
    Connection conn;
    Formatador objformatador = new Formatador();

    /**
     * Creates new form TelaCadastroMercadoria
     */
    public TelaCadastroProduto() {
        initComponents();
       // pesquisarProdutoC();
        pesquisarProduto();
        // listarDadosComboboxNomeFornecedor();
        LimparCampos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtFornecedor = new javax.swing.JTextField();
        txtProduto = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnPesquisarProduto = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluirProduto = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        btnLimpar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtValorCompra = new javax.swing.JTextField();
        txtValorVenda = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtLucro = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtPesquisarDesc = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        cbxNomeFornecedor = new javax.swing.JComboBox();
        cbxProdutoQueFornece = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(255, 235, 175));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastroproduto.png"))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("CADASTRO DE PRODUTOS");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtFornecedor.setVerifyInputWhenFocusTarget(false);

        txtProduto.setVerifyInputWhenFocusTarget(false);
        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(308, 308, 308)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(txtProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 235, 175));

        btnPesquisarProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnPesquisarProduto.setText("SAIR");
        btnPesquisarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarProdutoActionPerformed(evt);
            }
        });

        btnCadastrar.setBackground(new java.awt.Color(204, 255, 204));
        btnCadastrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCadastrar.setText("CADASTRAR");
        btnCadastrar.setMaximumSize(new java.awt.Dimension(89, 23));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(89, 23));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
        });
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnAlterar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAlterar.setText("ALTERAR");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluirProduto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnExcluirProduto.setText("EXCLUIR");
        btnExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirProdutoActionPerformed(evt);
            }
        });

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/JV - SISTAMASCADAST.png"))); // NOI18N

        btnLimpar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLimpar.setText("LIMPAR");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(btnAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnExcluirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(btnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnExcluirProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(btnLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnPesquisarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 235, 175));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel4.setText("CODIGO DO PRODUTO");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel6.setText("NOME DO FORNECEDOR*");

        jLabel7.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel7.setText("PRODUTO*");

        jLabel8.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel8.setText("QUANTIDADE*");

        jLabel9.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel9.setText("VALOR DA COMPRA*");

        jLabel10.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel10.setText("VALOR DE VENDA");

        txtQuantidade.setVerifyInputWhenFocusTarget(false);
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });

        txtValorCompra.setVerifyInputWhenFocusTarget(false);

        txtValorVenda.setVerifyInputWhenFocusTarget(false);
        txtValorVenda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorVendaFocusLost(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel11.setText("PERCENTUAL DE LUCRO*");

        txtLucro.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtLucro.setVerifyInputWhenFocusTarget(false);
        txtLucro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtLucroFocusLost(evt);
            }
        });
        txtLucro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLucroActionPerformed(evt);
            }
        });

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CÓDIGO", "FORNECEDOR", "PRODUTO", "QUANTIDADE", "VALOR  COMPRA", "VALOR DE VENDA", "LUCRO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaProduto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        tabelaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 54, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N

        txtId.setEnabled(false);
        txtId.setVerifyInputWhenFocusTarget(false);

        jLabel5.setText("Campos obrigatórios *");

        txtPesquisarDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesquisarDescActionPerformed(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesq cópia.PNG"))); // NOI18N
        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Bright", 0, 14)); // NOI18N
        jLabel13.setText("PESQUISAR");

        cbxNomeFornecedor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxNomeFornecedorItemStateChanged(evt);
            }
        });
        cbxNomeFornecedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxNomeFornecedorAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxNomeFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNomeFornecedorActionPerformed(evt);
            }
        });

        cbxProdutoQueFornece.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxProdutoQueForneceItemStateChanged(evt);
            }
        });
        cbxProdutoQueFornece.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                cbxProdutoQueForneceAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        cbxProdutoQueFornece.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxProdutoQueForneceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPesquisarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(122, 122, 122)
                                        .addComponent(jLabel1))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnBuscar))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel5))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(10, 10, 10))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbxNomeFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbxProdutoQueFornece, 0, 390, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLucro)
                                    .addComponent(txtValorVenda)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtValorCompra)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtValorCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(txtPesquisarDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbxNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10)
                    .addComponent(txtValorVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxProdutoQueFornece, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        txtLucro.getAccessibleContext().setAccessibleName("");
        txtLucro.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(1442, 723));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        AlterarProduto();
        pesquisarProduto();
       // pesquisarProdutoC();
        LimparCampos();

    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnPesquisarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarProdutoActionPerformed
        TelaMenu objtelamenu = new TelaMenu();
        objtelamenu.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnPesquisarProdutoActionPerformed

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        // TODO add your handling code here:
        if (tabelaProduto.getSelectedRow() != -1) {

            txtId.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 0).toString());
            //txtFornecedor.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 1).toString());
            cbxNomeFornecedor.setSelectedItem(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 1));
            cbxProdutoQueFornece.setSelectedItem(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 2));
            //txtProduto.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 2).toString());
            txtQuantidade.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 3).toString());
            txtValorCompra.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 4).toString());
            txtValorVenda.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 5).toString());
            txtLucro.setText(tabelaProduto.getValueAt(tabelaProduto.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void tabelaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProdutoKeyReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_tabelaProdutoKeyReleased

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        /*
        try {
            if(!txtQuantidade.getText().equals("")|| txtValorCompra.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Há campos em branco", "Cadastro de Produtos", JOptionPane.ERROR_MESSAGE);
            }else{
                double lucro = 0;
               // double numQuant = Double.parseDouble(txtQuantidade.getText());
                double numVC = Double.parseDouble(txtValorCompra.getText());
                double numVV = Double.parseDouble(txtValorVenda.getText());
                if(txtQuantidade.hasFocus()){
                    lucro = numVC - numVV;
                    
                }else{
                    txtLucro.setText(String.valueOf(lucro));
                }
            }
                
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null,"somente numeros" +erro);
        }
         */
        CadastrarProduto();
       // pesquisarProdutoC();
        pesquisarProduto();
       LimparCampos();
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirProdutoActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Realmente desesja excluir? Você perdera os dados"
                + "existentes no sistema", "ATENÇÃO",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            // yes option
            ExcluirProduto();
        } else {
            // no option
            LimparCampos();
        }

       // pesquisarProdutoC();
        pesquisarProduto();

    }//GEN-LAST:event_btnExcluirProdutoActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        LimparCampos();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked

    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtLucroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtLucroFocusLost
        // TODO add your handling code here:
        /* 
        double v;
        
        v = ((Double.parseDouble(txtValorCompra.getText()) *
                 Double.parseDouble(txtLucro.getText())) / 100) +
                 Double.parseDouble(txtValorCompra.getText());
        txtValorVenda.setText(String.valueOf(v));
         */
    }//GEN-LAST:event_txtLucroFocusLost

    private void txtLucroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLucroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLucroActionPerformed

    private void txtValorVendaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorVendaFocusLost
        // ele pega o valor da compra multiplica pelo lucro depois
        //devide por 100 e soma com o valor da compra(CALCULA A PORCENTAGEM PARA VENDA)

        double v;

        v = ((Double.parseDouble(txtValorCompra.getText().replace(",", "."))
                * Double.parseDouble(txtLucro.getText().replace(",", "."))) / 100)
                + Double.parseDouble(txtValorCompra.getText().replace(",", "."));
        txtValorVenda.setText(String.valueOf(v));
    }//GEN-LAST:event_txtValorVendaFocusLost

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        pesquisarProdutoDesc(txtPesquisarDesc.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtPesquisarDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesquisarDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisarDescActionPerformed

    private void cbxNomeFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNomeFornecedorActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbxNomeFornecedorActionPerformed

    private void cbxNomeFornecedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxNomeFornecedorItemStateChanged
        // TODO add your handling code here:
    
    }//GEN-LAST:event_cbxNomeFornecedorItemStateChanged

    private void cbxNomeFornecedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxNomeFornecedorAncestorAdded
        // TODO add your handling code here:
        FornecedorDAO dao = new FornecedorDAO();
        List<FornecedorDTO> lista = dao.PesquisarFornecedor();

        cbxNomeFornecedor.removeAll();

        for (FornecedorDTO f : lista) {
           cbxNomeFornecedor.addItem(f);
        }

    }//GEN-LAST:event_cbxNomeFornecedorAncestorAdded

    private void cbxProdutoQueForneceAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_cbxProdutoQueForneceAncestorAdded
        // TODO add your handling code here:

        FornecedorDAO dao = new FornecedorDAO();
        List<FornecedorDTO> lista = dao.PesquisarFornecedor();

        cbxProdutoQueFornece.removeAll();

       for (FornecedorDTO forn : lista) {
            cbxProdutoQueFornece.addItem(forn.getProduto_fornecedor());
        }
    }//GEN-LAST:event_cbxProdutoQueForneceAncestorAdded

    private void cbxProdutoQueForneceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxProdutoQueForneceItemStateChanged

        // TODO add your handling code here:
    }//GEN-LAST:event_cbxProdutoQueForneceItemStateChanged

    private void cbxProdutoQueForneceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxProdutoQueForneceActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_cbxProdutoQueForneceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnExcluirProduto;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisarProduto;
    private javax.swing.JComboBox cbxNomeFornecedor;
    private javax.swing.JComboBox cbxProdutoQueFornece;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProduto;
    private javax.swing.JTextField txtFornecedor;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLucro;
    private javax.swing.JTextField txtPesquisarDesc;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtValorCompra;
    private javax.swing.JTextField txtValorVenda;
    // End of variables declaration//GEN-END:variables
/*
    ////LISTAR DENTRO DA TABELA JA INSERIDO O COMBOBOX
    public void pesquisarProdutoC() {
        try {
            ProdutoDAO objprodutodao = new ProdutoDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaProduto.getModel();
            model.setNumRows(1);

            ArrayList<ProdutoDTO> lista = objprodutodao.pesquisarProdutoC();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getFornecedordto().getId_fornecedor(),
                    lista.get(num).getFornecedordto().getNome_fornecedor(),
                    lista.get(num).getFornecedordto().getProduto_fornecedor(),
                    lista.get(num).getQuantidade(),
                    lista.get(num).getValorcompra(),
                    lista.get(num).getValorvenda(),
                    lista.get(num).getLucro(),});
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores VIEW: " + erro);
        }
    }
*/
    
    public void pesquisarProduto() {
        try {
            ProdutoDAO objprodutodao = new ProdutoDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaProduto.getModel();
            model.setNumRows(1);

            ArrayList<ProdutoDTO> lista = objprodutodao.pesquisarProduto();

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getFornecedor(),
                    lista.get(num).getProduto(),
                    lista.get(num).getQuantidade(),
                    lista.get(num).getValorcompra(),
                    lista.get(num).getValorvenda(),
                    lista.get(num).getLucro(),});              
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores VIEW: " + erro);
        }
    }
     
    private void CadastrarProduto() {

        if (txtQuantidade.getText().equals("0")
                // ||txtFornecedor.getText().isEmpty()
                // ||txtProduto.getText().isEmpty()
                || txtValorCompra.getText().isEmpty()
                || txtValorVenda.getText().isEmpty()
                || txtLucro.getText().isEmpty()
                || txtQuantidade.getText().isEmpty()) {

            JOptionPane.showMessageDialog(null, "Os campos campos com * são obrigatórios!");
        } else {
            
            String quantidade, valorcompra, valorvenda, lucro;
            FornecedorDTO objfornecedordto = new FornecedorDTO();
            FornecedorDTO objfornecedor = new FornecedorDTO();
            //  codigo = txtCodigo.getText();
            //codfornecedor = id_fornecedor.get(cbxNomeFornecedor.getSelectedIndex()-1);
            objfornecedordto = (FornecedorDTO)
            cbxNomeFornecedor.getSelectedItem();
            cbxProdutoQueFornece.getSelectedItem();
            //fornecedor = txtFornecedor.getText();
            // produto = txtProduto.getText();
           // objfornecedor = (FornecedorDTO)cbxProdutoQueFornece.getSelectedItem();
            quantidade = txtQuantidade.getText();
            valorcompra = txtValorCompra.getText().replace(",", ".");
            valorvenda = txtValorVenda.getText().replace(",", ".");
            lucro = txtLucro.getText().replace(",", ".");

            ProdutoDTO objprodutodto = new ProdutoDTO();

            // objprodutodto.setCodigo(codigo);
            //objprodutodto.setCodigofornecedor(codfornecedor);
            //objprodutodto.setFornecedor(fornecedor);
            //objprodutodto.setProduto(produto);
            objprodutodto.setQuantidade(quantidade);
            objprodutodto.setValorcompra((valorcompra));
            objprodutodto.setLucro(lucro);
            objprodutodto.setValorvenda(valorvenda);
            objprodutodto.setFornecedordto(objfornecedordto);
            //objprodutodto.setFornecedordto(objfornecedordto);

            ProdutoDAO objprodutodao = new ProdutoDAO();
            objprodutodao.cadastrarProduto(objprodutodto);

        }
    }

    /*
    private void CarregarProduto() {
        int setar = tabelaProduto.getSelectedRow();
        
        txtId.setText(tabelaProduto.getModel().getValueAt(setar, 0).toString());
        txtCodigo.setText(tabelaProduto.getModel().getValueAt(setar, 1).toString());
        txtFornecedor.setText(tabelaProduto.getModel().getValueAt(setar, 2).toString());
        txtProduto.setText(tabelaProduto.getModel().getValueAt(setar, 3).toString());
        txtQuantidade.setText(tabelaProduto.getModel().getValueAt(setar, 4).toString());
        txtValorCompra.setText(tabelaProduto.getModel().getValueAt(setar, 5).toString());
        txtValorVenda.setText(tabelaProduto.getModel().getValueAt(setar, 6).toString());
        txtLucro.setText(tabelaProduto.getModel().getValueAt(setar,7).toString());
    }
     */
    private void LimparCampos() {
        //   txtCodigo.setText("");
        cbxNomeFornecedor.setSelectedItem("");
        //txtFornecedor.setText("");
        txtProduto.setText("");
        txtLucro.setText("");
        txtQuantidade.setText("");
        txtValorCompra.setText("");
        txtValorVenda.setText("");
        txtPesquisarDesc.setText("");

        txtProduto.requestFocus();

    }

    private void AlterarProduto() {

        String fornecedor, produto, lucro, quantidade, valorcompra, valorvenda;
        int id;

        //    codigo = txtCodigo.getText();
        fornecedor = txtFornecedor.getText();
        produto = txtProduto.getText();
        lucro = txtLucro.getText();
        quantidade = txtQuantidade.getText();
        valorcompra = txtValorCompra.getText();
        valorvenda = txtValorVenda.getText();
        id = Integer.parseInt(txtId.getText());

        ProdutoDTO objprodutodto = new ProdutoDTO();

        //   objprodutodto.setCodigo(codigo);
        objprodutodto.setFornecedor(fornecedor);
        objprodutodto.setProduto(produto);
        objprodutodto.setQuantidade(quantidade);
        objprodutodto.setLucro(lucro);
        objprodutodto.setValorcompra(valorcompra);
        objprodutodto.setValorvenda(valorvenda);
        objprodutodto.setId(id);

        ProdutoDAO objprodutodao = new ProdutoDAO();
        objprodutodao.alterarProduto(objprodutodto);

    }

    private void ExcluirProduto() {
        int id;

        id = Integer.parseInt(txtId.getText());

        ProdutoDTO objprodutodto = new ProdutoDTO();
        objprodutodto.setId(id);

        ProdutoDAO objprodutodao = new ProdutoDAO();
        objprodutodao.ExcluirProduto(objprodutodto);

    }

    //PESQUISAR PRODUTO DESCRIÇAO
    public void pesquisarProdutoDesc(String desc) {
        try {
            ProdutoDAO objprodutodao = new ProdutoDAO();

            DefaultTableModel model = (DefaultTableModel) tabelaProduto.getModel();
            model.setNumRows(1);

            ArrayList<ProdutoDTO> lista = objprodutodao.pesquisarProdutoDesc(desc);

            for (int num = 0; num < lista.size(); num++) {
                model.addRow(new Object[]{
                    lista.get(num).getId(),
                    lista.get(num).getProduto(),
                   lista.get(num).getFornecedor(),
                    lista.get(num).getQuantidade(),
                    lista.get(num).getValorcompra(),
                    lista.get(num).getValorvenda(),
                    lista.get(num).getLucro(),});
            }
        } catch (Exception erro) {
            JOptionPane.showMessageDialog(null, "listar valores desc VIEW: " + erro);
        }
    }
    /*
      Vector<Interger>id_fornecedor = new Vector<Interger>();
      //LISTAR FORNECEDOR NO COMBOX DA TABELA PRODUTO
      public void listarDadosComboboxNomeFornecedor(){
          
          try {
           ProdutoDAO objprodutodao = new ProdutoDAO();
           ResultSet rs = objprodutodao.listarFornecedor();

            while (rs.next()) {
              id_fornecedor.addElement(rs.getInt(1));
              cbxProdutoQueFornece.addItem(rs.getString(2));
            }
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "LISTAR FORNECEDOR VIEW" + erro);
        }
      }

     */
    
   
}